### ISSUE TITLE
Emitir token em sandbox só retorna invalid_client

### ISSUE THREAD

**Issue by ptheys** [OpenBanking-Brasil/specs-pcm#9]
Caros,

Estamos tentando gerar token no endpoint de emissão de tokens da PCM no ambiente de sandbox e só estamos recebendo invalid_client como resultado; a emissão com o mesmo certificado e client_id no endpoint de emissão de tokens do diretório de participantes em sandbox retorna um token com sucesso.

Tentamos chamar o endpoint de emissão com o formato JSON e form-urlencoded, ambos retornam invalid_client.

Estamos usando o client_id `JCB8Jj3IG9Cm36x5qOV2s`

Tem algum procedimento para provisionar os Software Statements do diretório na PCM?

Obrigado,

Patrick Theys

**Comment by escobera** [comment]
Estamos tendo o mesmo problema aqui.

**Comment by ptheys** [comment]
Passou a funcionar no dia 11/1/2023
